DROP DATABASE IF EXISTS STORE_DANI;
CREATE DATABASE IF NOT EXISTS `STORE_DANI` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `STORE_DANI`;

-- TABLE DOCUMENT_TYPE (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `DOCUMENT_TYPE`;
CREATE TABLE `DOCUMENT_TYPE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- TABLE ROLE (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `DESCRIPTION` TINYTEXT DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE PERSON (DEPENDS ON DOCUMENT_TYPE)
DROP TABLE IF EXISTS `PERSON`;
CREATE TABLE `PERSON` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(30) DEFAULT NULL,
  `LAST_NAME` VARCHAR(30) DEFAULT NULL,
  `ADDRESS` VARCHAR(70) DEFAULT NULL,
  `DOCUMENT_TYPE_ID` INT(11) DEFAULT NULL,
  `DOCUMENT_NUMBER` VARCHAR(12) DEFAULT NULL,
  `PHONE` VARCHAR(12) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `UPDATED_AT` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DOCUMENT_TYPE_ID` (`DOCUMENT_TYPE_ID`),
  CONSTRAINT `PERSON_IBFK_1` FOREIGN KEY (`DOCUMENT_TYPE_ID`) REFERENCES `DOCUMENT_TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

-- TABLE CUSTOMER (DEPENDS ON PERSON)
DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PERSON_ID` (`PERSON_ID`),
  CONSTRAINT `CUSTOMER_IBFK_1` FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSON` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

-- TABLE SUPPLIER (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `SUPPLIER`;
CREATE TABLE `SUPPLIER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `TAX_NUMBER` VARCHAR(12) DEFAULT NULL,
  `PHONE` VARCHAR(12) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `UPDATED_AT` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE CATEGORY (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `CATEGORY`;
CREATE TABLE `CATEGORY` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `DESCRIPTION` TINYTEXT DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;

-- TABLE PRODUCT (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `PRODUCT`;
CREATE TABLE `PRODUCT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `STOCK` INT(11) DEFAULT NULL,
  `PRICE` INT(11) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `IS_ACTIVE` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4;

-- TABLE PRODUCT_CATEGORY (DEPENDS ON PRODUCT AND CATEGORY)
DROP TABLE IF EXISTS `PRODUCT_CATEGORY`;
CREATE TABLE `PRODUCT_CATEGORY` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` INT(11) DEFAULT NULL,
  `PRODUCT_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  KEY `PRODUCT_ID` (`PRODUCT_ID`),
  CONSTRAINT `PRODUCT_CATEGORY_IBFK_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`),
  CONSTRAINT `PRODUCT_CATEGORY_IBFK_2` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

-- TABLE PRODUCT_SUPPLIER (DEPENDS ON PRODUCT AND SUPPLIER)
DROP TABLE IF EXISTS `PRODUCT_SUPPLIER`;
CREATE TABLE `PRODUCT_SUPPLIER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT(11) DEFAULT NULL,
  `SUPPLIER_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PRODUCT_ID` (`PRODUCT_ID`),
  KEY `SUPPLIER_ID` (`SUPPLIER_ID`),
  CONSTRAINT `PRODUCT_SUPPLIER_IBFK_1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`),
  CONSTRAINT `PRODUCT_SUPPLIER_IBFK_2` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `SUPPLIER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE INVOICE_STATUS (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `INVOICE_STATUS`;
CREATE TABLE `INVOICE_STATUS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `DESCRIPTION` TINYTEXT DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE INVOICE (DEPENDS ON CUSTOMER AND INVOICE_STATUS)
DROP TABLE IF EXISTS `INVOICE`;
CREATE TABLE `INVOICE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT(11) DEFAULT NULL,
  `STATUS_ID` INT(11) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `UPDATED_AT` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ID` (`CUSTOMER_ID`),
  KEY `STATUS_ID` (`STATUS_ID`),
  CONSTRAINT `INVOICE_IBFK_1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`),
  CONSTRAINT `INVOICE_IBFK_2` FOREIGN KEY (`STATUS_ID`) REFERENCES `INVOICE_STATUS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE INVOICE_PRODUCT (DEPENDS ON PRODUCT AND INVOICE)
DROP TABLE IF EXISTS `INVOICE_PRODUCT`;
CREATE TABLE `INVOICE_PRODUCT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT(11) DEFAULT NULL,
  `INVOICE_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PRODUCT_ID` (`PRODUCT_ID`),
  KEY `INVOICE_ID` (`INVOICE_ID`),
  CONSTRAINT `INVOICE_PRODUCT_IBFK_1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`),
  CONSTRAINT `INVOICE_PRODUCT_IBFK_2` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE ORDER_STATUS (NO FOREIGN KEY DEPENDENCIES)
DROP TABLE IF EXISTS `ORDER_STATUS`;
CREATE TABLE `ORDER_STATUS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE ORDER (DEPENDS ON INVOICE AND ORDER_STATUS)
DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `INVOICE_ID` INT(11) DEFAULT NULL,
  `STATUS_ID` INT(11) DEFAULT NULL,
  `DETAILS` TINYTEXT DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INVOICE_ID` (`INVOICE_ID`),
  KEY `STATUS_ID` (`STATUS_ID`),
  CONSTRAINT `ORDER_IBFK_1` FOREIGN KEY (`INVOICE_ID`) REFERENCES `INVOICE` (`ID`),
  CONSTRAINT `ORDER_IBFK_2` FOREIGN KEY (`STATUS_ID`) REFERENCES `ORDER_STATUS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE SELLER (DEPENDS ON DOCUMENT_TYPE AND ROLE)
DROP TABLE IF EXISTS `SELLER`;
CREATE TABLE `SELLER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(40) DEFAULT NULL,
  `LAST_NAME` VARCHAR(35) DEFAULT NULL,
  `DOCUMENT_TYPE_ID` INT(11) DEFAULT NULL,
  `DOCUMENT_NUMBER` VARCHAR(12) DEFAULT NULL,
  `ROLE_ID` INT(11) DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `UPDATED_AT` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DOCUMENT_TYPE_ID` (`DOCUMENT_TYPE_ID`),
  KEY `ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `SELLER_IBFK_1` FOREIGN KEY (`DOCUMENT_TYPE_ID`) REFERENCES `DOCUMENT_TYPE` (`ID`),
  CONSTRAINT `SELLER_IBFK_2` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
